spring:
  application:
    name: book-store
  datasource:
    url: jdbc:postgresql://localhost:5432/book_store
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      auto-commit: false


# JPA (Java Persistence API) Configuration
  jpa:
    hibernate:
      ddl-auto: update # You can also use "create" to create tables at startup
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method


logging:
  level:
    root: debug